###
GET http://localhost:3000/search


###
GET http://localhost:3000/search?q=Saar


###
GET http://localhost:3000/search?limit=22&type=language&shards=title

###
GET http://localhost:3000/search?domain=Chronontology&limit=1&shards=temporal_extends&shards=base
